AN-3
MineFactory-Resource/Announce pull request #1
Opened 2022-01-12 12:09 UTC by Fade-Jung

config 파일에 메세지 출력 간격 설정 추가

2022-01-12 12:51 UTC, Seokhun-Yang commented on src/main/java/teamuni/net/autoannounce/autoannounce.java
> +        String times = this.getConfig().getString("times");
times 는 문자열이 아닌 정수 아닌가요?

2022-01-13 04:49 UTC, LesserJang commented on src/main/java/teamuni/net/autoannounce/autoannounce.java
> +        String times = this.getConfig().getString("times");
`this.getConfig().getLong("times")` 으로 정수를 String으로 가져오는게 아니라 Long으로 가져왔으면 좋겠네요.

2022-01-13 08:33 UTC, abelbeak requested changes

2022-01-13 08:33 UTC, abelbeak commented on src/main/java/teamuni/net/autoannounce/autoannounce.java
> +        String times = this.getConfig().getString("times");
레서가 동일한 이의를 제기해서 Close

2022-01-13 08:33 UTC, abelbeak commented on src/main/java/teamuni/net/autoannounce/autoannounce.java
> +        String times = this.getConfig().getString("times");
이미 같은 부분에 이의를 제기한 사람이 있으면 거기에 COMMENT를 달것.

2022-01-13 08:33 UTC, abelbeak commented on autoannounce.iml
> +  </component>
imi, pom.xml 등의 파일은 사용자 환경에 따라 변경된느 파일들임.
Git Ignore에 추가하여 해당 파일을 Remote Repo에 저장하지 않아야 함.

2022-01-13 09:07 UTC, kari0707 approved these changes

2022-01-16 13:40 UTC, Seokhun-Yang approved these changes

2022-01-17 06:36 UTC, merged

2022-01-17 06:36 UTC, abelbeak commented
리뷰 미참여자: 라이