공지에 색깔 넣을 수 있게하기.
MineFactory-Resource/Announce pull request #4
Opened 2022-01-23 07:18 UTC by Fade-Jung

2022-01-23 07:21 UTC, Seokhun-Yang approved these changes

2022-01-23 07:36 UTC, All298Lie requested changes

2022-01-23 07:36 UTC, All298Lie commented on src/main/java/teamuni/net/autoannounce/autoannounce.java
> +                String msgBlack = (msgSplit.replace("&0", ChatColor.BLACK + ""));
변수를 불필요하게 많이 만드는 것 같고, ChatColor#translateAlternateColorCodes(char, String)에서 '&' 문자로 설정하시면 아래처럼 작성하실 필요 없어요.

2022-01-23 08:13 UTC, All298Lie approved these changes

2022-01-23 09:48 UTC, abelbeak approved these changes

2022-01-23 09:48 UTC, abelbeak commented
Pull Request Assigne 에는 레서와 아벨만 할당해주셔야 합니다.

2022-01-23 10:51 UTC, LesserJang approved these changes

2022-01-24 10:56 UTC, kari0707 approved these changes

2022-01-24 20:56 UTC, merged